//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPENgov.Acquisizioni {
    
    
    public partial class TestGridView {
        
        /// <summary>
        /// RibesGridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ribes.OPENgov.WebControls.RibesGridView RibesGridView1;
        
        /// <summary>
        /// RibesDateBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ribes.OPENgov.WebControls.RibesDateBox RibesDateBox1;
    }
}
