Imports System.Xml.Serialization
Imports log4net

Namespace AESpesometro
#Region "Oggetto XML"
    '------------------------------------------------------------------------------
    ' <auto-generated>
    '     This code was generated by a tool.
    '     Runtime Version:4.0.30319.42000
    '
    '     Changes to this file may cause incorrect behavior and will be lost if
    '     the code is regenerated.
    ' </auto-generated>
    '------------------------------------------------------------------------------
    ' 
    ' This source code was auto-generated by xsd, Version=4.6.1055.0.
    ' 
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0"),
 System.Xml.Serialization.XmlRootAttribute("DatiFattura", Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0", IsNullable:=False)>
    Public Class DatiFatturaType

        Private datiFatturaHeaderField As DatiFatturaHeaderType

        Private itemField As Object

        Private versioneField As VersioneType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiFatturaHeader As DatiFatturaHeaderType
            Get
                Return Me.datiFatturaHeaderField
            End Get
            Set
                Me.datiFatturaHeaderField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ANN", GetType(ANNType), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlElementAttribute("DTE", GetType(DTEType), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),
     System.Xml.Serialization.XmlElementAttribute("DTR", GetType(DTRType), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Item As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property versione As VersioneType
            Get
                Return Me.versioneField
            End Get
            Set
                Me.versioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiFatturaHeaderType

        Private progressivoInvioField As String

        Private dichiaranteField As DichiaranteType

        Private idSistemaField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property ProgressivoInvio As String
            Get
                Return Me.progressivoInvioField
            End Get
            Set
                Me.progressivoInvioField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Dichiarante As DichiaranteType
            Get
                Return Me.dichiaranteField
            End Get
            Set
                Me.dichiaranteField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdSistema As String
            Get
                Return Me.idSistemaField
            End Get
            Set
                Me.idSistemaField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DichiaranteType

        Private codiceFiscaleField As String

        Private caricaField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>
        Public Property Carica As String
            Get
                Return Me.caricaField
            End Get
            Set
                Me.caricaField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class ANNType

        Private idFileField As String

        Private posizioneField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property IdFile As String
            Get
                Return Me.idFileField
            End Get
            Set
                Me.idFileField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>
        Public Property Posizione As String
            Get
                Return Me.posizioneField
            End Get
            Set
                Me.posizioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiGeneraliDTRType

        Private tipoDocumentoField As TipoDocumentoType

        Private dataField As Date

        Private numeroField As String

        Private dataRegistrazioneField As Date

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property TipoDocumento As TipoDocumentoType
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>
        Public Property Data As Date
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Numero As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>
        Public Property DataRegistrazione As Date
            Get
                Return Me.dataRegistrazioneField
            End Get
            Set
                Me.dataRegistrazioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum TipoDocumentoType

        TD01

        TD04

        TD05

        TD07

        TD08

        TD10

        TD11
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiFatturaBodyDTRType

        Private datiGeneraliField As DatiGeneraliDTRType

        Private datiRiepilogoField() As DatiRiepilogoType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiGenerali As DatiGeneraliDTRType
            Get
                Return Me.datiGeneraliField
            End Get
            Set
                Me.datiGeneraliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DatiRiepilogo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiRiepilogo As DatiRiepilogoType()
            Get
                Return Me.datiRiepilogoField
            End Get
            Set
                Me.datiRiepilogoField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiRiepilogoType

        Private imponibileImportoField As Decimal

        Private datiIVAField As DatiIVAType

        Private naturaField As NaturaType

        Private naturaFieldSpecified As Boolean

        Private detraibileField As Decimal

        Private detraibileFieldSpecified As Boolean

        Private deducibileField As DeducibileType

        Private deducibileFieldSpecified As Boolean

        Private esigibilitaIVAField As EsigibilitaIVAType

        Private esigibilitaIVAFieldSpecified As Boolean

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property ImponibileImporto As Decimal
            Get
                Return Me.imponibileImportoField
            End Get
            Set
                Me.imponibileImportoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiIVA As DatiIVAType
            Get
                Return Me.datiIVAField
            End Get
            Set
                Me.datiIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Natura As NaturaType
            Get
                Return Me.naturaField
            End Get
            Set
                Me.naturaField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property NaturaSpecified As Boolean
            Get
                Return Me.naturaFieldSpecified
            End Get
            Set
                Me.naturaFieldSpecified = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Detraibile As Decimal
            Get
                Return Me.detraibileField
            End Get
            Set
                Me.detraibileField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property DetraibileSpecified As Boolean
            Get
                Return Me.detraibileFieldSpecified
            End Get
            Set
                Me.detraibileFieldSpecified = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Deducibile As DeducibileType
            Get
                Return Me.deducibileField
            End Get
            Set
                Me.deducibileField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property DeducibileSpecified As Boolean
            Get
                Return Me.deducibileFieldSpecified
            End Get
            Set
                Me.deducibileFieldSpecified = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property EsigibilitaIVA As EsigibilitaIVAType
            Get
                Return Me.esigibilitaIVAField
            End Get
            Set
                Me.esigibilitaIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property EsigibilitaIVASpecified As Boolean
            Get
                Return Me.esigibilitaIVAFieldSpecified
            End Get
            Set
                Me.esigibilitaIVAFieldSpecified = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiIVAType

        Private impostaField As Decimal

        Private impostaFieldSpecified As Boolean

        Private aliquotaField As Decimal

        Private aliquotaFieldSpecified As Boolean

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Imposta As Decimal
            Get
                Return Me.impostaField
            End Get
            Set
                Me.impostaField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ImpostaSpecified As Boolean
            Get
                Return Me.impostaFieldSpecified
            End Get
            Set
                Me.impostaFieldSpecified = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Aliquota As Decimal
            Get
                Return Me.aliquotaField
            End Get
            Set
                Me.aliquotaField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property AliquotaSpecified As Boolean
            Get
                Return Me.aliquotaFieldSpecified
            End Get
            Set
                Me.aliquotaFieldSpecified = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum NaturaType

        N1

        N2

        N3

        N4

        N5

        N6

        N7
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum DeducibileType

        SI
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum EsigibilitaIVAType

        D

        I

        S
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdentificativiFiscaliType

        Private idFiscaleIVAField As IdFiscaleType

        Private codiceFiscaleField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdFiscaleType

        Private idPaeseField As String

        Private idCodiceField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdPaese As String
            Get
                Return Me.idPaeseField
            End Get
            Set
                Me.idPaeseField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdCodice As String
            Get
                Return Me.idCodiceField
            End Get
            Set
                Me.idCodiceField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class CedentePrestatoreDTRType

        Private identificativiFiscaliField As IdentificativiFiscaliType

        Private altriDatiIdentificativiField As AltriDatiIdentificativiNoCAPType

        Private datiFatturaBodyDTRField() As DatiFatturaBodyDTRType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdentificativiFiscali As IdentificativiFiscaliType
            Get
                Return Me.identificativiFiscaliField
            End Get
            Set
                Me.identificativiFiscaliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property AltriDatiIdentificativi As AltriDatiIdentificativiNoCAPType
            Get
                Return Me.altriDatiIdentificativiField
            End Get
            Set
                Me.altriDatiIdentificativiField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DatiFatturaBodyDTR", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiFatturaBodyDTR As DatiFatturaBodyDTRType()
            Get
                Return Me.datiFatturaBodyDTRField
            End Get
            Set
                Me.datiFatturaBodyDTRField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class AltriDatiIdentificativiNoCAPType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType2

        Private sedeField As IndirizzoNoCAPType

        Private stabileOrganizzazioneField As IndirizzoType

        Private rappresentanteFiscaleField As RappresentanteFiscaleType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Nome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
     System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName As ItemsChoiceType2()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Sede As IndirizzoNoCAPType
            Get
                Return Me.sedeField
            End Get
            Set
                Me.sedeField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property StabileOrganizzazione As IndirizzoType
            Get
                Return Me.stabileOrganizzazioneField
            End Get
            Set
                Me.stabileOrganizzazioneField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RappresentanteFiscale As RappresentanteFiscaleType
            Get
                Return Me.rappresentanteFiscaleField
            End Get
            Set
                Me.rappresentanteFiscaleField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType2

        Cognome

        Unknown

        Denominazione

        Nome
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IndirizzoNoCAPType

        Private indirizzoField As String

        Private numeroCivicoField As String

        Private cAPField As String

        Private comuneField As String

        Private provinciaField As String

        Private nazioneField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Indirizzo As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NumeroCivico As String
            Get
                Return Me.numeroCivicoField
            End Get
            Set
                Me.numeroCivicoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CAP As String
            Get
                Return Me.cAPField
            End Get
            Set
                Me.cAPField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Comune As String
            Get
                Return Me.comuneField
            End Get
            Set
                Me.comuneField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Provincia As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Nazione As String
            Get
                Return Me.nazioneField
            End Get
            Set
                Me.nazioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IndirizzoType

        Private indirizzoField As String

        Private numeroCivicoField As String

        Private cAPField As String

        Private comuneField As String

        Private provinciaField As String

        Private nazioneField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Indirizzo As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NumeroCivico As String
            Get
                Return Me.numeroCivicoField
            End Get
            Set
                Me.numeroCivicoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CAP As String
            Get
                Return Me.cAPField
            End Get
            Set
                Me.cAPField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Comune As String
            Get
                Return Me.comuneField
            End Get
            Set
                Me.comuneField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Provincia As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Nazione As String
            Get
                Return Me.nazioneField
            End Get
            Set
                Me.nazioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class RappresentanteFiscaleType

        Private idFiscaleIVAField As IdFiscaleType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType3

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Nome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
     System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName As ItemsChoiceType3()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType3

        Cognome

        Unknown

        Denominazione

        Nome
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class CessionarioCommittenteDTRType

        Private identificativiFiscaliField As IdentificativiFiscaliITType

        Private altriDatiIdentificativiField As AltriDatiIdentificativiNoSedeType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdentificativiFiscali As IdentificativiFiscaliITType
            Get
                Return Me.identificativiFiscaliField
            End Get
            Set
                Me.identificativiFiscaliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property AltriDatiIdentificativi As AltriDatiIdentificativiNoSedeType
            Get
                Return Me.altriDatiIdentificativiField
            End Get
            Set
                Me.altriDatiIdentificativiField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdentificativiFiscaliITType

        Private idFiscaleIVAField As IdFiscaleITType

        Private codiceFiscaleField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA As IdFiscaleITType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdFiscaleITType

        Private idPaeseField As NazioneITType

        Private idCodiceField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdPaese As NazioneITType
            Get
                Return Me.idPaeseField
            End Get
            Set
                Me.idPaeseField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdCodice As String
            Get
                Return Me.idCodiceField
            End Get
            Set
                Me.idCodiceField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum NazioneITType

        IT
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class AltriDatiIdentificativiNoSedeType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType

        Private sedeField As IndirizzoType

        Private stabileOrganizzazioneField As IndirizzoType

        Private rappresentanteFiscaleField As RappresentanteFiscaleITType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Nome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
     System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Sede As IndirizzoType
            Get
                Return Me.sedeField
            End Get
            Set
                Me.sedeField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property StabileOrganizzazione As IndirizzoType
            Get
                Return Me.stabileOrganizzazioneField
            End Get
            Set
                Me.stabileOrganizzazioneField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RappresentanteFiscale As RappresentanteFiscaleITType
            Get
                Return Me.rappresentanteFiscaleField
            End Get
            Set
                Me.rappresentanteFiscaleField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType
        Cognome

        Unknown

        Denominazione

        Nome
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class RappresentanteFiscaleITType

        Private idFiscaleIVAField As IdFiscaleITIvaType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType1

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA As IdFiscaleITIvaType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlElementAttribute("Nome", GetType(System.String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
     System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdFiscaleITIvaType

        Private idPaeseField As NazioneITType

        Private idCodiceField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdPaese As NazioneITType
            Get
                Return Me.idPaeseField
            End Get
            Set
                Me.idPaeseField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdCodice As String
            Get
                Return Me.idCodiceField
            End Get
            Set
                Me.idCodiceField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType1

        Cognome

        Unknown
        Denominazione

        Nome
    End Enum
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DTRType

        Private cessionarioCommittenteDTRField As CessionarioCommittenteDTRType

        Private cedentePrestatoreDTRField() As CedentePrestatoreDTRType

        Private rettificaField As RettificaType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CessionarioCommittenteDTR As CessionarioCommittenteDTRType
            Get
                Return Me.cessionarioCommittenteDTRField
            End Get
            Set
                Me.cessionarioCommittenteDTRField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CedentePrestatoreDTR", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CedentePrestatoreDTR As CedentePrestatoreDTRType()
            Get
                Return Me.cedentePrestatoreDTRField
            End Get
            Set
                Me.cedentePrestatoreDTRField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Rettifica As RettificaType
            Get
                Return Me.rettificaField
            End Get
            Set
                Me.rettificaField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class RettificaType

        Private idFileField As String

        Private posizioneField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property IdFile As String
            Get
                Return Me.idFileField
            End Get
            Set
                Me.idFileField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="integer")>
        Public Property Posizione As String
            Get
                Return Me.posizioneField
            End Get
            Set
                Me.posizioneField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiGeneraliType

        Private tipoDocumentoField As TipoDocumentoType

        Private dataField As Date

        Private numeroField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property TipoDocumento As TipoDocumentoType
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>
        Public Property Data As Date
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Numero As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DatiFatturaBodyDTEType

        Private datiGeneraliField As DatiGeneraliType

        Private datiRiepilogoField() As DatiRiepilogoType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiGenerali As DatiGeneraliType
            Get
                Return Me.datiGeneraliField
            End Get
            Set
                Me.datiGeneraliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DatiRiepilogo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiRiepilogo As DatiRiepilogoType()
            Get
                Return Me.datiRiepilogoField
            End Get
            Set
                Me.datiRiepilogoField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class IdentificativiFiscaliNoIVAType

        Private idFiscaleIVAField As IdFiscaleType

        Private codiceFiscaleField As String

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class CessionarioCommittenteDTEType

        Private identificativiFiscaliField As IdentificativiFiscaliNoIVAType

        Private altriDatiIdentificativiField As AltriDatiIdentificativiNoCAPType

        Private datiFatturaBodyDTEField() As DatiFatturaBodyDTEType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdentificativiFiscali As IdentificativiFiscaliNoIVAType
            Get
                Return Me.identificativiFiscaliField
            End Get
            Set
                Me.identificativiFiscaliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property AltriDatiIdentificativi As AltriDatiIdentificativiNoCAPType
            Get
                Return Me.altriDatiIdentificativiField
            End Get
            Set
                Me.altriDatiIdentificativiField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DatiFatturaBodyDTE", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiFatturaBodyDTE As DatiFatturaBodyDTEType()
            Get
                Return Me.datiFatturaBodyDTEField
            End Get
            Set
                Me.datiFatturaBodyDTEField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class CedentePrestatoreDTEType

        Private identificativiFiscaliField As IdentificativiFiscaliITType

        Private altriDatiIdentificativiField As AltriDatiIdentificativiNoSedeType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdentificativiFiscali As IdentificativiFiscaliITType
            Get
                Return Me.identificativiFiscaliField
            End Get
            Set
                Me.identificativiFiscaliField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property AltriDatiIdentificativi As AltriDatiIdentificativiNoSedeType
            Get
                Return Me.altriDatiIdentificativiField
            End Get
            Set
                Me.altriDatiIdentificativiField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Class DTEType

        Private cedentePrestatoreDTEField As CedentePrestatoreDTEType

        Private cessionarioCommittenteDTEField() As CessionarioCommittenteDTEType

        Private rettificaField As RettificaType

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CedentePrestatoreDTE As CedentePrestatoreDTEType
            Get
                Return Me.cedentePrestatoreDTEField
            End Get
            Set
                Me.cedentePrestatoreDTEField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CessionarioCommittenteDTE", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CessionarioCommittenteDTE As CessionarioCommittenteDTEType()
            Get
                Return Me.cessionarioCommittenteDTEField
            End Get
            Set
                Me.cessionarioCommittenteDTEField = Value
            End Set
        End Property

        ''' <remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Rettifica As RettificaType
            Get
                Return Me.rettificaField
            End Get
            Set
                Me.rettificaField = Value
            End Set
        End Property
    End Class
    ''' <remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute(Namespace:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v2.0")>
    Public Enum VersioneType

        DAT20
    End Enum
#End Region
#Region "Metodi"
    Public Class ClsAESpesometro
        Private Shared Log As ILog = LogManager.GetLogger(GetType(ClsAESpesometro))

        Public Function ExctractSpesometro(IdEnte As String, Anno As String) As String
            Try
                Dim mySpesometro As DatiFatturaType = GetSpesometro(IdEnte, Anno)
                If Not mySpesometro Is Nothing Then
                    Return SerializeObj(mySpesometro)
                Else
                    Return ""
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.AESpesometro.ExctractSpesometro.errore: ", ex)
                Return ""
            End Try
        End Function
        Private Function GetSpesometro(IdEnte As String, Anno As String) As DatiFatturaType
            Try
                Dim mySpesometro As New DatiFatturaType
                Dim myDatiFatturaHeader As New DatiFatturaHeaderType
                Dim myDTE As New DTEType
                Dim myCedentePrestatoreDTE As New CedentePrestatoreDTEType
                Dim myIdentificativiFiscali As New IdentificativiFiscaliITType
                Dim myIdFiscaleIT As New IdFiscaleITType
                Dim myIdFiscale As New IdFiscaleType
                Dim myAltriDatiIdentificativiNoSede As New AltriDatiIdentificativiNoSedeType
                Dim myIndirizzo As New IndirizzoType
                Dim ListCessionarioCommittenteDTE As New ArrayList
                Dim dtMyDati As New DataTable()
                Dim dtMyRow As DataRow
                Dim x As Integer = 0

                dtMyDati = GetDati(IdEnte, Anno)
                If Not dtMyDati Is Nothing Then
                    For Each dtMyRow In dtMyDati.Rows
                        myDatiFatturaHeader.ProgressivoInvio = CStr(dtMyRow("progressivoinvio"))
                        mySpesometro.DatiFatturaHeader = myDatiFatturaHeader

                        myIdentificativiFiscali = New IdentificativiFiscaliITType
                        myIdFiscaleIT = New IdFiscaleITType
                        myIdFiscaleIT.IdPaese = NazioneITType.IT
                        myIdFiscaleIT.IdCodice = CStr(dtMyRow("idcodicecedente"))
                        myIdentificativiFiscali.IdFiscaleIVA = myIdFiscaleIT
                        myIdentificativiFiscali.CodiceFiscale = CStr(dtMyRow("cfcedente"))
                        myCedentePrestatoreDTE.IdentificativiFiscali = myIdentificativiFiscali

                        ReDim Preserve myAltriDatiIdentificativiNoSede.ItemsElementName(1)
                        ReDim Preserve myAltriDatiIdentificativiNoSede.Items(1)
                        myAltriDatiIdentificativiNoSede.ItemsElementName(0) = ItemsChoiceType2.Denominazione
                        myAltriDatiIdentificativiNoSede.Items(0) = CStr(dtMyRow("denominazionecedente"))
                        myIndirizzo = New IndirizzoType
                        myIndirizzo.CAP = CStr(dtMyRow("capcedente"))
                        myIndirizzo.Comune = CStr(dtMyRow("comunecedente"))
                        myIndirizzo.Indirizzo = CStr(dtMyRow("indirizzocedente"))
                        myIndirizzo.Nazione = CStr(dtMyRow("nazionecedente"))
                        myIndirizzo.Provincia = CStr(dtMyRow("pvcedente"))

                        myAltriDatiIdentificativiNoSede.Sede = myIndirizzo
                        myCedentePrestatoreDTE.AltriDatiIdentificativi = myAltriDatiIdentificativiNoSede

                        Dim myCessionarioCommittenteDTE As New CessionarioCommittenteDTEType
                        Dim myIdentificativiFiscaliNoIVA As New IdentificativiFiscaliNoIVAType
                        Dim myDatiFatturaBodyDTE As New DatiFatturaBodyDTEType
                        Dim myDatiRiepilogo As New DatiRiepilogoType
                        Dim myDatiIVA As New DatiIVAType
                        Dim myDatiGenerali As New DatiGeneraliType
                        Dim myAltriDatiIdentificativiNoCAP As New AltriDatiIdentificativiNoCAPType
                        Dim myIndNoCAP As New IndirizzoNoCAPType
                        myIdFiscale = New IdFiscaleType
                        myIdFiscale.IdPaese = CStr(dtMyRow("idpaese"))
                        myIdFiscale.IdCodice = CStr(dtMyRow("cfpiva"))
                        myIdentificativiFiscaliNoIVA.IdFiscaleIVA = myIdFiscale
                        myCessionarioCommittenteDTE.IdentificativiFiscali = myIdentificativiFiscaliNoIVA

                        If myIdFiscale.IdCodice.Length > 11 Then
                            ReDim Preserve myAltriDatiIdentificativiNoCAP.ItemsElementName(2)
                            ReDim Preserve myAltriDatiIdentificativiNoCAP.Items(2)
                            myAltriDatiIdentificativiNoCAP.ItemsElementName(0) = ItemsChoiceType2.Cognome
                            myAltriDatiIdentificativiNoCAP.Items(0) = CStr(dtMyRow("cognome"))
                            myAltriDatiIdentificativiNoCAP.ItemsElementName(1) = ItemsChoiceType2.Nome
                            myAltriDatiIdentificativiNoCAP.Items(1) = CStr(dtMyRow("nome"))
                        Else
                            ReDim Preserve myAltriDatiIdentificativiNoCAP.ItemsElementName(1)
                            ReDim Preserve myAltriDatiIdentificativiNoCAP.Items(1)
                            myAltriDatiIdentificativiNoCAP.ItemsElementName(0) = ItemsChoiceType2.Denominazione
                            myAltriDatiIdentificativiNoCAP.Items(0) = CStr(dtMyRow("cognome"))
                        End If
                        myIndNoCAP = New IndirizzoNoCAPType
                        myIndNoCAP.CAP = CStr(dtMyRow("cap"))
                        myIndNoCAP.Comune = CStr(dtMyRow("comune"))
                        myIndNoCAP.Indirizzo = CStr(dtMyRow("indirizzo"))
                        myIndNoCAP.Nazione = CStr(dtMyRow("nazione"))
                        myIndNoCAP.Provincia = CStr(dtMyRow("pv"))

                        myAltriDatiIdentificativiNoCAP.Sede = myIndNoCAP
                        myCessionarioCommittenteDTE.AltriDatiIdentificativi = myAltriDatiIdentificativiNoCAP

                        myDatiGenerali.TipoDocumento = TipoDocumentoType.TD01 'CStr(dtMyRow("tipodocumento"))
                        myDatiGenerali.Data = CDate(dtMyRow("data"))
                        myDatiGenerali.Numero = CStr(dtMyRow("numero"))
                        myDatiFatturaBodyDTE.DatiGenerali = myDatiGenerali

                        myDatiIVA.AliquotaSpecified = True
                        myDatiIVA.ImpostaSpecified = True
                        myDatiIVA.Aliquota = CDec(dtMyRow("aliquota"))
                        myDatiIVA.Imposta = CDec(dtMyRow("imposta"))
                        myDatiRiepilogo.DatiIVA = myDatiIVA
                        myDatiRiepilogo.ImponibileImporto = CDec(dtMyRow("imponibileimporto"))
                        myDatiRiepilogo.EsigibilitaIVA = EsigibilitaIVAType.I 'CStr(dtMyRow("esigibilitaiva"))
                        ReDim Preserve myDatiFatturaBodyDTE.DatiRiepilogo(1)
                        myDatiFatturaBodyDTE.DatiRiepilogo(0) = myDatiRiepilogo

                        ReDim Preserve myCessionarioCommittenteDTE.DatiFatturaBodyDTE(1)
                        myCessionarioCommittenteDTE.DatiFatturaBodyDTE(0) = myDatiFatturaBodyDTE

                        ListCessionarioCommittenteDTE.Add(myCessionarioCommittenteDTE)
                        x += 1
                    Next
                    myDTE.CedentePrestatoreDTE = myCedentePrestatoreDTE
                    myDTE.CessionarioCommittenteDTE = CType(ListCessionarioCommittenteDTE.ToArray(GetType(CessionarioCommittenteDTEType)), CessionarioCommittenteDTEType())
                    mySpesometro.Item = myDTE
                    mySpesometro.versione = VersioneType.DAT20
                    Return mySpesometro
                Else
                    Return Nothing
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.AESpesometro.GetSpesometro.errore: ", ex)
                Return Nothing
            End Try
        End Function
        Private Function SerializeObj(obj As Object) As String
            Try
                Dim MyFile As String = "SPESOMETRO.xml"
                Dim xs As New System.Xml.Serialization.XmlSerializer(obj.GetType)
                Dim w As New IO.StringWriter
                xs.Serialize(w, obj)
                If IO.File.Exists(ConstSession.PathFileAE + MyFile) Then
                    IO.File.Delete(ConstSession.PathFileAE + MyFile)
                End If
                MyUtility.WriteFile(ConstSession.PathFileAE + MyFile, w.ToString)
                Return MyFile
            Catch Err As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.AESpesometro.SerializeObj.errore: ", Err)
                Return ""
            End Try
        End Function
        Private Function GetDati(IdEnte As String, Anno As String) As DataTable
            Dim cmdMyCommand As New SqlClient.SqlCommand
            Dim myAdapter As New SqlClient.SqlDataAdapter
            Dim dtMyDati As New DataTable()

            Try
                cmdMyCommand.Connection = New SqlClient.SqlConnection(ConstSession.StringConnection)
                cmdMyCommand.Connection.Open()
                cmdMyCommand.CommandTimeout = 0
                cmdMyCommand.CommandType = CommandType.StoredProcedure
                cmdMyCommand.CommandText = "prc_GetAESpesometro"
                'valorizzo i parameters:
                cmdMyCommand.Parameters.Clear()
                cmdMyCommand.Parameters.Add(New SqlClient.SqlParameter("@IDENTE", SqlDbType.NVarChar)).Value = IdEnte
                cmdMyCommand.Parameters.Add(New SqlClient.SqlParameter("@ANNO", SqlDbType.NVarChar)).Value = Anno
                myAdapter.SelectCommand = cmdMyCommand
                myAdapter.Fill(dtMyDati)
                Return dtMyDati
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.AESpesometro.GetSpesometro.errore: ", ex)
                Return Nothing
            Finally
                myAdapter.Dispose()
                cmdMyCommand.Dispose()
                cmdMyCommand.Connection.Close()
            End Try
        End Function
    End Class
#End Region
End Namespace
