'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports log4net

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace WSOPENae

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceOPENaeSoap", [Namespace]:="http://localhost/OPENaeWS/")>
    Partial Public Class ServiceOPENae
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private PopolaTabAppoggioAEOperationCompleted As System.Threading.SendOrPostCallback

        Private PopolaTabAppoggioAE1OperationCompleted As System.Threading.SendOrPostCallback

        Private EstraiTracciatoAEOperationCompleted As System.Threading.SendOrPostCallback

        Private GetFlussiTracciatiAEOperationCompleted As System.Threading.SendOrPostCallback

        Private PopolaTabAppoggioAE2OperationCompleted As System.Threading.SendOrPostCallback

        Private EstraiTracciatoAE1OperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean
        Private Shared Log As ILog = LogManager.GetLogger(GetType(ServiceOPENae))

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://sec.isimply.it/OPENaews/ServiceOPENae.asmx"
            Try
                If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                    Me.UseDefaultCredentials = True
                    Me.useDefaultCredentialsSetExplicitly = False
                Else
                    Me.useDefaultCredentialsSetExplicitly = True
                End If

            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.New.errore: ", ex)
            End Try
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                            AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
                    MyBase.UseDefaultCredentials = False
                End If
                MyBase.Url = Value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = Value
                Me.useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        '''<remarks/>
        Public Event PopolaTabAppoggioAECompleted As PopolaTabAppoggioAECompletedEventHandler

        '''<remarks/>
        Public Event PopolaTabAppoggioAE1Completed As PopolaTabAppoggioAE1CompletedEventHandler

        '''<remarks/>
        Public Event EstraiTracciatoAECompleted As EstraiTracciatoAECompletedEventHandler

        '''<remarks/>
        Public Event GetFlussiTracciatiAECompleted As GetFlussiTracciatiAECompletedEventHandler

        '''<remarks/>
        Public Event PopolaTabAppoggioAE2Completed As PopolaTabAppoggioAE2CompletedEventHandler

        '''<remarks/>
        Public Event EstraiTracciatoAE1Completed As EstraiTracciatoAE1CompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaQuery", RequestElementName:="PopolaDaQuery", RequestNamespace:="http://localhost/OPENaeWS/", ResponseElementName:="PopolaDaQueryResponse", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Overloads Function PopolaTabAppoggioAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String) As <System.Xml.Serialization.XmlElementAttribute("PopolaDaQueryResult")> Boolean
            Try
                Dim results() As Object = Me.Invoke("PopolaTabAppoggioAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT})
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginPopolaTabAppoggioAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PopolaTabAppoggioAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndPopolaTabAppoggioAE(ByVal asyncResult As System.IAsyncResult) As Boolean
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndPopolaTabAppoggioAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAEAsync(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String)
            Me.PopolaTabAppoggioAEAsync(sTributo, sAnnoRif, sCodiceISTAT, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAEAsync(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal userState As Object)
            Try
                If (Me.PopolaTabAppoggioAEOperationCompleted Is Nothing) Then
                    Me.PopolaTabAppoggioAEOperationCompleted = AddressOf Me.OnPopolaTabAppoggioAEOperationCompleted
                End If
                Me.InvokeAsync("PopolaTabAppoggioAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT}, Me.PopolaTabAppoggioAEOperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAEAsync.errore: ", ex)
            End Try
        End Sub

        Private Sub OnPopolaTabAppoggioAEOperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.PopolaTabAppoggioAECompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent PopolaTabAppoggioAECompleted(Me, New PopolaTabAppoggioAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnPopolaTabAppoggioAEOperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="PopolaTabAppoggioAE1"),
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaOggetti", RequestElementName:="PopolaDaOggetti", RequestNamespace:="http://localhost/OPENaeWS/", ResponseElementName:="PopolaDaOggettiResponse", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Overloads Function PopolaTabAppoggioAE(ByVal oDati() As DisposizioneAE) As <System.Xml.Serialization.XmlElementAttribute("PopolaDaOggettiResult")> Boolean
            Try
                Dim results() As Object = Me.Invoke("PopolaTabAppoggioAE1", New Object() {oDati})
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginPopolaTabAppoggioAE1(ByVal oDati() As DisposizioneAE, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PopolaTabAppoggioAE1", New Object() {oDati}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndPopolaTabAppoggioAE1(ByVal asyncResult As System.IAsyncResult) As Boolean
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndPopolaTabAppoggioAE1.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAE1Async(ByVal oDati() As DisposizioneAE)
            Me.PopolaTabAppoggioAE1Async(oDati, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAE1Async(ByVal oDati() As DisposizioneAE, ByVal userState As Object)
            Try
                If (Me.PopolaTabAppoggioAE1OperationCompleted Is Nothing) Then
                    Me.PopolaTabAppoggioAE1OperationCompleted = AddressOf Me.OnPopolaTabAppoggioAE1OperationCompleted
                End If
                Me.InvokeAsync("PopolaTabAppoggioAE1", New Object() {oDati}, Me.PopolaTabAppoggioAE1OperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAE1Async.errore: ", ex)
            End Try
        End Sub

        Private Sub OnPopolaTabAppoggioAE1OperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.PopolaTabAppoggioAE1CompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent PopolaTabAppoggioAE1Completed(Me, New PopolaTabAppoggioAE1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnPopolaTabAppoggioAE1OperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/EstraiTracciatoAE", RequestNamespace:="http://localhost/OPENaeWS/", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Overloads Function EstraiTracciatoAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByRef sNomeFileTracciati As String) As String
            Try
                Dim results() As Object = Me.Invoke("EstraiTracciatoAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sNomeFileTracciati})
                sNomeFileTracciati = CType(results(1), String)
                Return CType(results(0), String)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EstraiTracciatoAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginEstraiTracciatoAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sNomeFileTracciati As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EstraiTracciatoAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sNomeFileTracciati}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndEstraiTracciatoAE(ByVal asyncResult As System.IAsyncResult, ByRef sNomeFileTracciati As String) As String
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                sNomeFileTracciati = CType(results(1), String)
                Return CType(results(0), String)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndEstraiTracciatAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub EstraiTracciatoAEAsync(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sNomeFileTracciati As String)
            Me.EstraiTracciatoAEAsync(sTributo, sAnnoRif, sCodiceISTAT, sNomeFileTracciati, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub EstraiTracciatoAEAsync(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sNomeFileTracciati As String, ByVal userState As Object)
            Try
                If (Me.EstraiTracciatoAEOperationCompleted Is Nothing) Then
                    Me.EstraiTracciatoAEOperationCompleted = AddressOf Me.OnEstraiTracciatoAEOperationCompleted
                End If
                Me.InvokeAsync("EstraiTracciatoAE", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sNomeFileTracciati}, Me.EstraiTracciatoAEOperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EstraiTracciatoAEAsync.errore: ", ex)
            End Try
        End Sub

        Private Sub OnEstraiTracciatoAEOperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.EstraiTracciatoAECompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent EstraiTracciatoAECompleted(Me, New EstraiTracciatoAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnEstraiTracciatoAEOperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/GetFlussiTracciati", RequestElementName:="GetFlussiTracciati", RequestNamespace:="http://localhost/OPENaeWS/", ResponseElementName:="GetFlussiTracciatiResponse", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Function GetFlussiTracciatiAE(ByVal sTributo As String, ByVal sCodiceISTAT As String, ByRef sMyErr As String) As <System.Xml.Serialization.XmlArrayAttribute("GetFlussiTracciatiResult")> objFlussoAE()
            Try
                Dim results() As Object = Me.Invoke("GetFlussiTracciatiAE", New Object() {sTributo, sCodiceISTAT, sMyErr})
                sMyErr = CType(results(1), String)
                Return CType(results(0), objFlussoAE())
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.GetFlussiTracciatiAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginGetFlussiTracciatiAE(ByVal sTributo As String, ByVal sCodiceISTAT As String, ByVal sMyErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFlussiTracciatiAE", New Object() {sTributo, sCodiceISTAT, sMyErr}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndGetFlussiTracciatiAE(ByVal asyncResult As System.IAsyncResult, ByRef sMyErr As String) As objFlussoAE()
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                sMyErr = CType(results(1), String)
                Return CType(results(0), objFlussoAE())
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndGetFlussiTracciatiAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub GetFlussiTracciatiAEAsync(ByVal sTributo As String, ByVal sCodiceISTAT As String, ByVal sMyErr As String)
            Me.GetFlussiTracciatiAEAsync(sTributo, sCodiceISTAT, sMyErr, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub GetFlussiTracciatiAEAsync(ByVal sTributo As String, ByVal sCodiceISTAT As String, ByVal sMyErr As String, ByVal userState As Object)
            Try
                If (Me.GetFlussiTracciatiAEOperationCompleted Is Nothing) Then
                    Me.GetFlussiTracciatiAEOperationCompleted = AddressOf Me.OnGetFlussiTracciatiAEOperationCompleted
                End If
                Me.InvokeAsync("GetFlussiTracciatiAE", New Object() {sTributo, sCodiceISTAT, sMyErr}, Me.GetFlussiTracciatiAEOperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.GetFlussiTracciatiAEAsync.errore: ", ex)
            End Try
        End Sub

        Private Sub OnGetFlussiTracciatiAEOperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.GetFlussiTracciatiAECompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent GetFlussiTracciatiAECompleted(Me, New GetFlussiTracciatiAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnGetFlussiTracciatiAEOperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="PopolaTabAppoggioAE2"),
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaFile", RequestElementName:="PopolaDaFile", RequestNamespace:="http://localhost/OPENaeWS/", ResponseElementName:="PopolaDaFileResponse", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Overloads Function PopolaTabAppoggioAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sFileImport As String, ByVal sProvenienza As String) As <System.Xml.Serialization.XmlElementAttribute("PopolaDaFileResult")> Boolean
            Try
                Dim results() As Object = Me.Invoke("PopolaTabAppoggioAE2", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sFileImport, sProvenienza})
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginPopolaTabAppoggioAE2(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sFileImport As String, ByVal sProvenienza As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PopolaTabAppoggioAE2", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sFileImport, sProvenienza}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndPopolaTabAppoggioAE2(ByVal asyncResult As System.IAsyncResult) As Boolean
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                Return CType(results(0), Boolean)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndPopolaTabAppoggioAE2.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAE2Async(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sFileImport As String, ByVal sProvenienza As String)
            Me.PopolaTabAppoggioAE2Async(sTributo, sAnnoRif, sCodiceISTAT, sFileImport, sProvenienza, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub PopolaTabAppoggioAE2Async(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sFileImport As String, ByVal sProvenienza As String, ByVal userState As Object)
            Try
                If (Me.PopolaTabAppoggioAE2OperationCompleted Is Nothing) Then
                    Me.PopolaTabAppoggioAE2OperationCompleted = AddressOf Me.OnPopolaTabAppoggioAE2OperationCompleted
                End If
                Me.InvokeAsync("PopolaTabAppoggioAE2", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sFileImport, sProvenienza}, Me.PopolaTabAppoggioAE2OperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.PopolaTabAppoggioAE2Async.errore: ", ex)
            End Try
        End Sub

        Private Sub OnPopolaTabAppoggioAE2OperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.PopolaTabAppoggioAE2CompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent PopolaTabAppoggioAE2Completed(Me, New PopolaTabAppoggioAE2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnPopolaTabAppoggioAE2OperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        <System.Web.Services.WebMethodAttribute(MessageName:="EstraiTracciatoAE1"),
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/EstraiICI", RequestElementName:="EstraiICI", RequestNamespace:="http://localhost/OPENaeWS/", ResponseElementName:="EstraiICIResponse", ResponseNamespace:="http://localhost/OPENaeWS/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
        Public Overloads Function EstraiTracciatoAE(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sCodBelfiore As String, ByVal sDescrEnte As String, ByVal sCAPEnte As String, ByVal sDataScadenza As String, ByVal nProgInvio As Integer, ByRef sNomeFileTracciati As String) As <System.Xml.Serialization.XmlElementAttribute("EstraiICIResult")> String
            Try
                Dim results() As Object = Me.Invoke("EstraiTracciatoAE1", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sCodBelfiore, sDescrEnte, sCAPEnte, sDataScadenza, nProgInvio, sNomeFileTracciati})
                sNomeFileTracciati = CType(results(1), String)
                Return CType(results(0), String)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EstraiTracciatoAE.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Function BeginEstraiTracciatoAE1(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sCodBelfiore As String, ByVal sDescrEnte As String, ByVal sCAPEnte As String, ByVal sDataScadenza As String, ByVal nProgInvio As Integer, ByVal sNomeFileTracciati As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EstraiTracciatoAE1", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sCodBelfiore, sDescrEnte, sCAPEnte, sDataScadenza, nProgInvio, sNomeFileTracciati}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndEstraiTracciatoAE1(ByVal asyncResult As System.IAsyncResult, ByRef sNomeFileTracciati As String) As String
            Try
                Dim results() As Object = Me.EndInvoke(asyncResult)
                sNomeFileTracciati = CType(results(1), String)
                Return CType(results(0), String)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EndEstraiTracciatoAE1.errore: ", ex)
            End Try
        End Function

        '''<remarks/>
        Public Overloads Sub EstraiTracciatoAE1Async(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sCodBelfiore As String, ByVal sDescrEnte As String, ByVal sCAPEnte As String, ByVal sDataScadenza As String, ByVal nProgInvio As Integer, ByVal sNomeFileTracciati As String)
            Me.EstraiTracciatoAE1Async(sTributo, sAnnoRif, sCodiceISTAT, sCodBelfiore, sDescrEnte, sCAPEnte, sDataScadenza, nProgInvio, sNomeFileTracciati, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub EstraiTracciatoAE1Async(ByVal sTributo As String, ByVal sAnnoRif As String, ByVal sCodiceISTAT As String, ByVal sCodBelfiore As String, ByVal sDescrEnte As String, ByVal sCAPEnte As String, ByVal sDataScadenza As String, ByVal nProgInvio As Integer, ByVal sNomeFileTracciati As String, ByVal userState As Object)
            Try
                If (Me.EstraiTracciatoAE1OperationCompleted Is Nothing) Then
                    Me.EstraiTracciatoAE1OperationCompleted = AddressOf Me.OnEstraiTracciatoAE1OperationCompleted
                End If
                Me.InvokeAsync("EstraiTracciatoAE1", New Object() {sTributo, sAnnoRif, sCodiceISTAT, sCodBelfiore, sDescrEnte, sCAPEnte, sDataScadenza, nProgInvio, sNomeFileTracciati}, Me.EstraiTracciatoAE1OperationCompleted, userState)
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.EstraiTracciatoAE1sync.errore: ", ex)
            End Try
        End Sub

        Private Sub OnEstraiTracciatoAE1OperationCompleted(ByVal arg As Object)
            Try
                If (Not (Me.EstraiTracciatoAE1CompletedEvent) Is Nothing) Then
                    Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                    RaiseEvent EstraiTracciatoAE1Completed(Me, New EstraiTracciatoAE1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
                End If
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.OnEstraiTracciatoAE1OperationCompleted.errore: ", ex)
            End Try
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            Try
                If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                    Return False
                End If
                Dim wsUri As System.Uri = New System.Uri(url)
                If ((wsUri.Port >= 1024) _
                            AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                    Return True
                End If
                Return False
            Catch ex As Exception
                Log.Debug(ConstSession.IdEnte +"."+ ConstSession.UserName + " - OPENgovH2O.ServiceOPENae.IsLocalFileSystemWebService.errore: ", ex)
            End Try
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Partial Public Class DisposizioneAE

        Private nIDDisposizioneField As Integer

        Private nIDCollegamentoField As Integer

        Private nIDFlussoField As Integer

        Private nIDContribuenteField As Integer

        Private nMesiFatturazioneField As Integer

        Private nConsumoField As Integer

        Private nImportoFatturatoField As Double

        Private nIDTitoloOccupazioneField As TitoloOccupazione

        Private nIDTipoOccupanteField As NaturaOccupazione

        Private nIDDestinazioneUsoField As DestinazioneUso

        Private nIDAssenzaDatiCatastaliField As AssenzaDatiCatastali

        Private nIDTipoUtenzaField As TipologiaUtenza

        Private sCodISTATField As String

        Private sTributoField As String

        Private sAnnoField As String

        Private sCodFiscaleEnteField As String

        Private sCognomeEnteField As String

        Private sNomeEnteField As String

        Private sSessoEnteField As String

        Private sDataNascitaEnteField As String

        Private sComuneNascitaSedeEnteField As String

        Private sPVNascitaSedeEnteField As String

        Private sCodFiscaleField As String

        Private sCognomeField As String

        Private sNomeField As String

        Private sSessoField As String

        Private sDataNascitaField As String

        Private sComuneNascitaSedeField As String

        Private sPVNascitaSedeField As String

        Private sComuneDomFiscField As String

        Private sPVDomFiscField As String

        Private sEstremiContrattoField As String

        Private sTipoContrattoField As String

        Private sDataInizioField As String

        Private sDataFineField As String

        Private sComuneAmmUbicazioneField As String

        Private sPVAmmUbicazioneField As String

        Private sComuneCatastUbicazioneField As String

        Private sCodComuneUbicazioneCatastField As String

        Private sIDTipoUnitaField As String

        Private sSezioneField As String

        Private sFoglioField As String

        Private sParticellaField As String

        Private sEstensioneParticellaField As String

        Private sIDTipoParticellaField As String

        Private sSubalternoField As String

        Private sIndirizzoField As String

        Private sCivicoField As String

        Private sInternoField As String

        Private sScalaField As String

        Private sSegnoField As String

        '''<remarks/>
        Public Property nIDDisposizione() As Integer
            Get
                Return Me.nIDDisposizioneField
            End Get
            Set
                Me.nIDDisposizioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDCollegamento() As Integer
            Get
                Return Me.nIDCollegamentoField
            End Get
            Set
                Me.nIDCollegamentoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDFlusso() As Integer
            Get
                Return Me.nIDFlussoField
            End Get
            Set
                Me.nIDFlussoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDContribuente() As Integer
            Get
                Return Me.nIDContribuenteField
            End Get
            Set
                Me.nIDContribuenteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nMesiFatturazione() As Integer
            Get
                Return Me.nMesiFatturazioneField
            End Get
            Set
                Me.nMesiFatturazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nConsumo() As Integer
            Get
                Return Me.nConsumoField
            End Get
            Set
                Me.nConsumoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nImportoFatturato() As Double
            Get
                Return Me.nImportoFatturatoField
            End Get
            Set
                Me.nImportoFatturatoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDTitoloOccupazione() As TitoloOccupazione
            Get
                Return Me.nIDTitoloOccupazioneField
            End Get
            Set
                Me.nIDTitoloOccupazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDTipoOccupante() As NaturaOccupazione
            Get
                Return Me.nIDTipoOccupanteField
            End Get
            Set
                Me.nIDTipoOccupanteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDDestinazioneUso() As DestinazioneUso
            Get
                Return Me.nIDDestinazioneUsoField
            End Get
            Set
                Me.nIDDestinazioneUsoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDAssenzaDatiCatastali() As AssenzaDatiCatastali
            Get
                Return Me.nIDAssenzaDatiCatastaliField
            End Get
            Set
                Me.nIDAssenzaDatiCatastaliField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property nIDTipoUtenza() As TipologiaUtenza
            Get
                Return Me.nIDTipoUtenzaField
            End Get
            Set
                Me.nIDTipoUtenzaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCodISTAT() As String
            Get
                Return Me.sCodISTATField
            End Get
            Set
                Me.sCodISTATField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sTributo() As String
            Get
                Return Me.sTributoField
            End Get
            Set
                Me.sTributoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sAnno() As String
            Get
                Return Me.sAnnoField
            End Get
            Set
                Me.sAnnoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCodFiscaleEnte() As String
            Get
                Return Me.sCodFiscaleEnteField
            End Get
            Set
                Me.sCodFiscaleEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCognomeEnte() As String
            Get
                Return Me.sCognomeEnteField
            End Get
            Set
                Me.sCognomeEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sNomeEnte() As String
            Get
                Return Me.sNomeEnteField
            End Get
            Set
                Me.sNomeEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sSessoEnte() As String
            Get
                Return Me.sSessoEnteField
            End Get
            Set
                Me.sSessoEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sDataNascitaEnte() As String
            Get
                Return Me.sDataNascitaEnteField
            End Get
            Set
                Me.sDataNascitaEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sComuneNascitaSedeEnte() As String
            Get
                Return Me.sComuneNascitaSedeEnteField
            End Get
            Set
                Me.sComuneNascitaSedeEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sPVNascitaSedeEnte() As String
            Get
                Return Me.sPVNascitaSedeEnteField
            End Get
            Set
                Me.sPVNascitaSedeEnteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCodFiscale() As String
            Get
                Return Me.sCodFiscaleField
            End Get
            Set
                Me.sCodFiscaleField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCognome() As String
            Get
                Return Me.sCognomeField
            End Get
            Set
                Me.sCognomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sNome() As String
            Get
                Return Me.sNomeField
            End Get
            Set
                Me.sNomeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sSesso() As String
            Get
                Return Me.sSessoField
            End Get
            Set
                Me.sSessoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sDataNascita() As String
            Get
                Return Me.sDataNascitaField
            End Get
            Set
                Me.sDataNascitaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sComuneNascitaSede() As String
            Get
                Return Me.sComuneNascitaSedeField
            End Get
            Set
                Me.sComuneNascitaSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sPVNascitaSede() As String
            Get
                Return Me.sPVNascitaSedeField
            End Get
            Set
                Me.sPVNascitaSedeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sComuneDomFisc() As String
            Get
                Return Me.sComuneDomFiscField
            End Get
            Set
                Me.sComuneDomFiscField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sPVDomFisc() As String
            Get
                Return Me.sPVDomFiscField
            End Get
            Set
                Me.sPVDomFiscField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sEstremiContratto() As String
            Get
                Return Me.sEstremiContrattoField
            End Get
            Set
                Me.sEstremiContrattoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sTipoContratto() As String
            Get
                Return Me.sTipoContrattoField
            End Get
            Set
                Me.sTipoContrattoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sDataInizio() As String
            Get
                Return Me.sDataInizioField
            End Get
            Set
                Me.sDataInizioField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sDataFine() As String
            Get
                Return Me.sDataFineField
            End Get
            Set
                Me.sDataFineField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sComuneAmmUbicazione() As String
            Get
                Return Me.sComuneAmmUbicazioneField
            End Get
            Set
                Me.sComuneAmmUbicazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sPVAmmUbicazione() As String
            Get
                Return Me.sPVAmmUbicazioneField
            End Get
            Set
                Me.sPVAmmUbicazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sComuneCatastUbicazione() As String
            Get
                Return Me.sComuneCatastUbicazioneField
            End Get
            Set
                Me.sComuneCatastUbicazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCodComuneUbicazioneCatast() As String
            Get
                Return Me.sCodComuneUbicazioneCatastField
            End Get
            Set
                Me.sCodComuneUbicazioneCatastField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sIDTipoUnita() As String
            Get
                Return Me.sIDTipoUnitaField
            End Get
            Set
                Me.sIDTipoUnitaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sSezione() As String
            Get
                Return Me.sSezioneField
            End Get
            Set
                Me.sSezioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sFoglio() As String
            Get
                Return Me.sFoglioField
            End Get
            Set
                Me.sFoglioField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sParticella() As String
            Get
                Return Me.sParticellaField
            End Get
            Set
                Me.sParticellaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sEstensioneParticella() As String
            Get
                Return Me.sEstensioneParticellaField
            End Get
            Set
                Me.sEstensioneParticellaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sIDTipoParticella() As String
            Get
                Return Me.sIDTipoParticellaField
            End Get
            Set
                Me.sIDTipoParticellaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sSubalterno() As String
            Get
                Return Me.sSubalternoField
            End Get
            Set
                Me.sSubalternoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sIndirizzo() As String
            Get
                Return Me.sIndirizzoField
            End Get
            Set
                Me.sIndirizzoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sCivico() As String
            Get
                Return Me.sCivicoField
            End Get
            Set
                Me.sCivicoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sInterno() As String
            Get
                Return Me.sInternoField
            End Get
            Set
                Me.sInternoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sScala() As String
            Get
                Return Me.sScalaField
            End Get
            Set
                Me.sScalaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property sSegno() As String
            Get
                Return Me.sSegnoField
            End Get
            Set
                Me.sSegnoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Public Enum TitoloOccupazione

        '''<remarks/>
        NonSpecificato

        '''<remarks/>
        Proprieta

        '''<remarks/>
        Usufrutto

        '''<remarks/>
        Locazione_AltroDiritto

        '''<remarks/>
        AltroDiritto_Rappresentante
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Public Enum NaturaOccupazione

        '''<remarks/>
        NonSpecificato

        '''<remarks/>
        Singolo

        '''<remarks/>
        NucleoFamiliare

        '''<remarks/>
        AttivitaCommerciale

        '''<remarks/>
        AltraTipologia
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Public Enum DestinazioneUso

        '''<remarks/>
        NonSpecificato

        '''<remarks/>
        Abitativo

        '''<remarks/>
        TenutoADisposizione

        '''<remarks/>
        Commerciale

        '''<remarks/>
        Box

        '''<remarks/>
        AltriUsi
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Public Enum AssenzaDatiCatastali

        '''<remarks/>
        NonSpecificato

        '''<remarks/>
        NonAccatastato

        '''<remarks/>
        NonAccatastabile

        '''<remarks/>
        DatiNonDisponibili_Preesistente

        '''<remarks/>
        OmessaDichiarazione

        '''<remarks/>
        FornitureTemporanee

        '''<remarks/>
        Condominii
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Public Enum TipologiaUtenza

        '''<remarks/>
        NonSpecificato

        '''<remarks/>
        DomesticaRes

        '''<remarks/>
        DomesticaNonRes

        '''<remarks/>
        NonDomestica

        '''<remarks/>
        GrandeUtenza
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://localhost/OPENaeWS/")>
    Partial Public Class objFlussoAE

        Private idFlussoField As Integer

        Private codiceISTATField As String

        Private annoField As String

        Private nomeFileField As String

        Private dataEstrazioneField As String

        Private numeroUtentiField As Integer

        Private numeroRecordsField As Integer

        Private numeroArticoliField As Integer

        '''<remarks/>
        Public Property IdFlusso() As Integer
            Get
                Return Me.idFlussoField
            End Get
            Set
                Me.idFlussoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodiceISTAT() As String
            Get
                Return Me.codiceISTATField
            End Get
            Set
                Me.codiceISTATField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Anno() As String
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NomeFile() As String
            Get
                Return Me.nomeFileField
            End Get
            Set
                Me.nomeFileField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DataEstrazione() As String
            Get
                Return Me.dataEstrazioneField
            End Get
            Set
                Me.dataEstrazioneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroUtenti() As Integer
            Get
                Return Me.numeroUtentiField
            End Get
            Set
                Me.numeroUtentiField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroRecords() As Integer
            Get
                Return Me.numeroRecordsField
            End Get
            Set
                Me.numeroRecordsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroArticoli() As Integer
            Get
                Return Me.numeroArticoliField
            End Get
            Set
                Me.numeroArticoliField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub PopolaTabAppoggioAECompletedEventHandler(ByVal sender As Object, ByVal e As PopolaTabAppoggioAECompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class PopolaTabAppoggioAECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Boolean)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub PopolaTabAppoggioAE1CompletedEventHandler(ByVal sender As Object, ByVal e As PopolaTabAppoggioAE1CompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class PopolaTabAppoggioAE1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Boolean)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub EstraiTracciatoAECompletedEventHandler(ByVal sender As Object, ByVal e As EstraiTracciatoAECompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class EstraiTracciatoAECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property sNomeFileTracciati() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(1), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub GetFlussiTracciatiAECompletedEventHandler(ByVal sender As Object, ByVal e As GetFlussiTracciatiAECompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class GetFlussiTracciatiAECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As objFlussoAE()
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), objFlussoAE())
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property sMyErr() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(1), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub PopolaTabAppoggioAE2CompletedEventHandler(ByVal sender As Object, ByVal e As PopolaTabAppoggioAE2CompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class PopolaTabAppoggioAE2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), Boolean)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>
    Public Delegate Sub EstraiTracciatoAE1CompletedEventHandler(ByVal sender As Object, ByVal e As EstraiTracciatoAE1CompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class EstraiTracciatoAE1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property

        '''<remarks/>
        Public ReadOnly Property sNomeFileTracciati() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(1), String)
            End Get
        End Property
    End Class
End Namespace
