'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Letture

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContatore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboImpianto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboImpianto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboUbicazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUbicazione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtVia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNCivico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNCivico As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEsponente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEsponente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGiro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSequenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSequenza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLatoStrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLatoStrada As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboPosizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPosizione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProgressivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgressivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTipoContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTipoContatore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCifreContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCifreContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataAttivazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAttivazione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataSostituzione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSostituzione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataRimTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataRimTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataCessazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataCessazione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTipoUtenze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTipoUtenze As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumeroUtenze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroUtenze As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkEsenteAcqua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteAcqua As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteAcquaQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteAcquaQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteFognatura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteFognatura As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteFogQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteFogQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteDepurazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteDepurazione As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteDepQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteDepQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNoteContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoteContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdLetture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdLetture As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''btnReloadGrdLetture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReloadGrdLetture As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServ As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAppoggio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAppoggio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConferma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConferma As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCodContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodVecchioContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodVecchioContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAppoggioGriglia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAppoggioGriglia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtIDGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDGiro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSetPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSetPosition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIDPosizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDPosizione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIDAnomalia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDAnomalia As Global.System.Web.UI.WebControls.TextBox
End Class
