'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DatiGeneraliContr

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnEliminaContratto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEliminaContratto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HDtxtCodIntestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDtxtCodIntestatario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HDTextCodUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDTextCodUtente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRibalta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRibalta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRibaltaAnagAnater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRibaltaAnagAnater As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtidContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalcolaNU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalcolaNU As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIdentificativoContratto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificativoContratto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataSottoscr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSottoscr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNumeroUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroUtente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastIdContratto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastIdContratto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAttivaContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAttivaContatore As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblattcont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblattcont As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnApriIntestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApriIntestatario As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LnkAnagAnater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkAnagAnater As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtCognomeIntestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCognomeIntestatario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodiceFiscaleIntestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodiceFiscaleIntestatario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtViaIntestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViaIntestatario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnApriUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApriUtente As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LnkAnagrAnatUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkAnagrAnatUtente As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtCognomeUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCognomeUtente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodiceFiscaleUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodiceFiscaleUtente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtViaUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViaUtente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LnkOpenStradario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkOpenStradario As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LnkPulisciStrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkPulisciStrada As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtEnteAppartenenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnteAppartenenza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtVia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCodVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodVia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCivico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCivico As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEsponente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEsponente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblResRifCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResRifCat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdRifCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRifCat As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''cboImpianto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboImpianto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGiro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSequenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSequenza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboPosizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPosizione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProgressivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgressivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLatoStrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLatoStrada As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTipoContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTipoContatore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumeroCifreContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroCifreContatore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboDiametroContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDiametroContatore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboDiametroPresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDiametroPresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboTipoUtenze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTipoUtenze As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumeroUtenze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroUtenze As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkEsenteAcqua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteAcqua As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteAcquaQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteAcquaQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cboFognatura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFognatura As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkEsenteFognatura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteFognatura As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteDepQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteDepQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cboDepurazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDepurazione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkEsenteDepurazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteDepurazione As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEsenteFogQF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEsenteFogQF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDataAttivazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAttivazione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataSospsensioneUtenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSospsensioneUtenza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataCessazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataCessazione As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkRichiestaSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRichiestaSub As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNoteSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoteSub As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTitOccupazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTitOccupazione As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoUtenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoUtenza As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoUnita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoUnita As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAssenzaDatiCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAssenzaDatiCat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtspesaprev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtspesaprev As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdirittisegr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdirittisegr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboMinimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMinimi As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboStatoContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatoContatore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''miointestatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents miointestatario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mioutente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mioutente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDataCessazioneRibaltata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDataCessazioneRibaltata As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdCodAnagrafeUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCodAnagrafeUtente As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnEvento2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEvento2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bntCalcolaNumeroUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntCalcolaNumeroUtente As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStampa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampa2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfIDContatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIDContatore As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''IDContratto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDContratto As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdMatricola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdMatricola As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
