'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestRuolo

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitolo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents info As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TxtNDelibera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNDelibera As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInizioDelibera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInizioDelibera As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFineDelibera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFineDelibera As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DivRiepilogoDaElab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivRiepilogoDaElab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlAnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAnno As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chk8852 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk8852 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTASI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTASI As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk0434 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk0434 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk0453 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk0453 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDalNotifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDalNotifica As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAlNotifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlNotifica As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlProvenienza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProvenienza As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkInteressi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInteressi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSpese control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSpese As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdDateElaborazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdDateElaborazione As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''FileEstratto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileEstratto As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblFile290 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFile290 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdPosizioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdPosizioni As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''GrdRuoliPrec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliPrec As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''DivAttesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivAttesa As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblAvanzamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAvanzamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CmdCalcola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdCalcola As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdApprova control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdApprova As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdEstrai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdEstrai As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdScarica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdScarica As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdStampa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdOld As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfIdRuolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdRuolo As Global.System.Web.UI.WebControls.HiddenField
End Class
