'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Calcolo

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents info As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblTipoMQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTipoMQ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optFlusso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optFlusso As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtInizioConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInizioConf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFineConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFineConf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGGScadenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGGScadenza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSimulazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSimulazione As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fuMyFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuMyFiles As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblNoteFlussi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoteFlussi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblIntestTesBidoneDaElab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblIntestTesBidoneDaElab As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fsRuoliImportati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsRuoliImportati As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GrdRuoliImportati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliImportati As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''LblAvanzamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAvanzamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblResultRuoliVsCatPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResultRuoliVsCatPF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdRuoliVsCatPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliVsCatPF As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''LblResultRuoliVsCatPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResultRuoliVsCatPV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdRuoliVsCatPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliVsCatPV As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''LblResultRuoliVsCatPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResultRuoliVsCatPM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdRuoliVsCatPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliVsCatPM As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''LblResultRuoliVsCatPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResultRuoliVsCatPC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdRuoliVsCatPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdRuoliVsCatPC As Global.Ribes.OPENgov.WebControls.RibesGridView

    '''<summary>
    '''CmdVisualizza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdVisualizza As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdDownload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CmdUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfIdRuoloMinutaAvvisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdRuoloMinutaAvvisi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdMinutaAnagAllRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdMinutaAnagAllRow As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdMinutaStampatoreAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdMinutaStampatoreAllowed As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdIsMinutaXStampatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdIsMinutaXStampatore As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdPFPVUniqueRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdPFPVUniqueRow As Global.System.Web.UI.WebControls.HiddenField
End Class
