'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace PAGINA

    Partial Public Class FormAnagrafica

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblEnti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnti As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlEnti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEnti As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblOperation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOperation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblConcurrencyMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConcurrencyMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''GestResidenti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GestResidenti As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''DivDatiResidenti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DivDatiResidenti As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LblAzione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblAzione As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblCodFiscaleRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblCodFiscaleRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblCognomeRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblCognomeRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblNomeRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblNomeRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblSessoRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblSessoRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblComuneNasRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblComuneNasRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblDataNasRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblDataNasRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblDataMorteRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblDataMorteRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblIndirizzoRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblIndirizzoRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblCodFamigliaRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblCodFamigliaRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LblParentelaRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblParentelaRes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DivAttesa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DivAttesa As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtCodiceFiscale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCodiceFiscale As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPartitaIva control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPartitaIva As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCognome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCognome As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cboSesso control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSesso As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtLuogoNascita control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLuogoNascita As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProvinciaNascita control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProvinciaNascita As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDataNascita control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataNascita As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDataMorte control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataMorte As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkSplitPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSplitPayment As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtSplitCod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSplitCod As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNazionalitaNascita control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNazionalitaNascita As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNucleoFamiliare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNucleoFamiliare As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtComuneResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComuneResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCAPResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCAPResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProvinciaResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProvinciaResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtViaResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViaResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFrazioneResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrazioneResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNumeroCivicoResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumeroCivicoResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPosizioneResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPosizioneResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEsponenteCivicoResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEsponenteCivicoResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtScalaResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScalaResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtInternoResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInternoResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNazionalitaResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNazionalitaResidenza As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''GrdInvio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GrdInvio As Global.Ribes.OPENgov.WebControls.RibesGridView

        '''<summary>
        '''DivIndSped control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DivIndSped As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hdIdSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIdSpedizione As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ddlTributo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTributo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCognomeSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCognomeSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNomeSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNomeSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtComuneSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComuneSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCAPSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCAPSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProvinciaSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProvinciaSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtIndirizzoSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIndirizzoSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFrazioneSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFrazioneSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNumeroCivicoSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumeroCivicoSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPosizioneSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPosizioneSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEsponenteSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEsponenteSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtScalaSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtScalaSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtInternoSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInternoSpedizione As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgContatti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgContatti As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''cboTipoContatto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTipoContatto As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtDatiRiferimento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDatiRiferimento As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkInvioInformativeViaMail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkInvioInformativeViaMail As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtDataInizioInvio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDataInizioInvio As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''GrdTributi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GrdTributi As Global.Ribes.OPENgov.WebControls.RibesGridView

        '''<summary>
        '''txtNoteAnagrafica control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoteAnagrafica As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkDaRicontrollare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDaRicontrollare As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnEvento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEvento As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCodiceFiscaleServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCodiceFiscaleServer As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDaCodiceFiscaleServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDaCodiceFiscaleServer As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAction As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnConfermaContatti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfermaContatti As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnEliminaContatti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEliminaContatti As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CommandAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommandAction As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnLock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLock As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSalva control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSalva As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnControlloCINSalva control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnControlloCINSalva As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancella control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancella As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnAnnulla control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAnnulla As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hdIdContribuente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIdContribuente As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdIdAnagrafica control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdIdAnagrafica As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCodComuneNascita control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCodComuneNascita As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCODRappresentanteLegale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCODRappresentanteLegale As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCODViaResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCODViaResidenza As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCodComuneResidenza control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCodComuneResidenza As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCODViaSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCODViaSpedizione As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdCodComuneSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCodComuneSpedizione As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''CmdSaveSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CmdSaveSpedizione As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CmdUnloadSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CmdUnloadSpedizione As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CmdRibaltaSpedizione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CmdRibaltaSpedizione As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
