//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DichiarazioniICI.WServiceOPENae {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using log4net;
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceOPENaeSoap", Namespace="http://localhost/OPENaeWS/")]
    public partial class ServiceOPENae : System.Web.Services.Protocols.SoapHttpClientProtocol {
        private static readonly ILog log = LogManager.GetLogger(typeof(ServiceOPENae));
        private System.Threading.SendOrPostCallback PopolaTabAppoggioAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopolaTabAppoggioAE1OperationCompleted;
        
        private System.Threading.SendOrPostCallback EstraiTracciatoAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlussiTracciatiAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopolaTabAppoggioAE2OperationCompleted;
        
        private System.Threading.SendOrPostCallback EstraiTracciatoAE1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceOPENae() {
            this.Url = "https://sec.isimply.it/OPENaews/ServiceOPENae.asmx";
            try { 
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.ServiceOPENae.errore: ", Err);
            }

        }


        public new string Url {
            get {
                return base.Url;
            }
            set {
                try { 
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
                }
                catch (Exception Err)
                {
                    log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.Url.errore: ", Err);
                }
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PopolaTabAppoggioAECompletedEventHandler PopolaTabAppoggioAECompleted;
        
        /// <remarks/>
        public event PopolaTabAppoggioAE1CompletedEventHandler PopolaTabAppoggioAE1Completed;
        
        /// <remarks/>
        public event EstraiTracciatoAECompletedEventHandler EstraiTracciatoAECompleted;
        
        /// <remarks/>
        public event GetFlussiTracciatiAECompletedEventHandler GetFlussiTracciatiAECompleted;
        
        /// <remarks/>
        public event PopolaTabAppoggioAE2CompletedEventHandler PopolaTabAppoggioAE2Completed;
        
        /// <remarks/>
        public event EstraiTracciatoAE1CompletedEventHandler EstraiTracciatoAE1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaQuery", RequestElementName="PopolaDaQuery", RequestNamespace="http://localhost/OPENaeWS/", ResponseElementName="PopolaDaQueryResponse", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PopolaDaQueryResult")]
        public bool PopolaTabAppoggioAE(string sTributo, string sAnnoRif, string sCodiceISTAT) {
            object[] results = this.Invoke("PopolaTabAppoggioAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPopolaTabAppoggioAE(string sTributo, string sAnnoRif, string sCodiceISTAT, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PopolaTabAppoggioAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndPopolaTabAppoggioAE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAEAsync(string sTributo, string sAnnoRif, string sCodiceISTAT) {
            this.PopolaTabAppoggioAEAsync(sTributo, sAnnoRif, sCodiceISTAT, null);
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAEAsync(string sTributo, string sAnnoRif, string sCodiceISTAT, object userState) {
            try { 
            if ((this.PopolaTabAppoggioAEOperationCompleted == null)) {
                this.PopolaTabAppoggioAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopolaTabAppoggioAEOperationCompleted);
            }
            this.InvokeAsync("PopolaTabAppoggioAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT}, this.PopolaTabAppoggioAEOperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.PopolaTabAppoggioAEAsync.errore: ", Err);
            }
        }
        
        private void OnPopolaTabAppoggioAEOperationCompleted(object arg) {
            try { 
            if ((this.PopolaTabAppoggioAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopolaTabAppoggioAECompleted(this, new PopolaTabAppoggioAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnPopolaTabAppoggioAEOperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="PopolaTabAppoggioAE1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaOggetti", RequestElementName="PopolaDaOggetti", RequestNamespace="http://localhost/OPENaeWS/", ResponseElementName="PopolaDaOggettiResponse", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PopolaDaOggettiResult")]
        public bool PopolaTabAppoggioAE(DisposizioneAE[] oDati) {
            object[] results = this.Invoke("PopolaTabAppoggioAE1", new object[] {
                        oDati});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPopolaTabAppoggioAE1(DisposizioneAE[] oDati, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PopolaTabAppoggioAE1", new object[] {
                        oDati}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndPopolaTabAppoggioAE1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAE1Async(DisposizioneAE[] oDati) {
            this.PopolaTabAppoggioAE1Async(oDati, null);
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAE1Async(DisposizioneAE[] oDati, object userState) {
            try { 
            if ((this.PopolaTabAppoggioAE1OperationCompleted == null)) {
                this.PopolaTabAppoggioAE1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopolaTabAppoggioAE1OperationCompleted);
            }
            this.InvokeAsync("PopolaTabAppoggioAE1", new object[] {
                        oDati}, this.PopolaTabAppoggioAE1OperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.PopolaTabAppoggioAE1Async.errore: ", Err);
            }
        }
        
        private void OnPopolaTabAppoggioAE1OperationCompleted(object arg) {
            try { 
            if ((this.PopolaTabAppoggioAE1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopolaTabAppoggioAE1Completed(this, new PopolaTabAppoggioAE1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnPopolaTabAppoggioAE1OperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/EstraiTracciatoAE", RequestNamespace="http://localhost/OPENaeWS/", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EstraiTracciatoAE(string sTributo, string sAnnoRif, string sCodiceISTAT, ref string sNomeFileTracciati) {
            object[] results = this.Invoke("EstraiTracciatoAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sNomeFileTracciati});
            sNomeFileTracciati = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEstraiTracciatoAE(string sTributo, string sAnnoRif, string sCodiceISTAT, string sNomeFileTracciati, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EstraiTracciatoAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sNomeFileTracciati}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndEstraiTracciatoAE(System.IAsyncResult asyncResult, out string sNomeFileTracciati) {
            object[] results = this.EndInvoke(asyncResult);
            sNomeFileTracciati = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EstraiTracciatoAEAsync(string sTributo, string sAnnoRif, string sCodiceISTAT, string sNomeFileTracciati) {
            this.EstraiTracciatoAEAsync(sTributo, sAnnoRif, sCodiceISTAT, sNomeFileTracciati, null);
        }
        
        /// <remarks/>
        public void EstraiTracciatoAEAsync(string sTributo, string sAnnoRif, string sCodiceISTAT, string sNomeFileTracciati, object userState) {
            try { 
            if ((this.EstraiTracciatoAEOperationCompleted == null)) {
                this.EstraiTracciatoAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstraiTracciatoAEOperationCompleted);
            }
            this.InvokeAsync("EstraiTracciatoAE", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sNomeFileTracciati}, this.EstraiTracciatoAEOperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.EstraiTracciatoAEAsync.errore: ", Err);
            }
        }
        
        private void OnEstraiTracciatoAEOperationCompleted(object arg) {
            try { 
            if ((this.EstraiTracciatoAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstraiTracciatoAECompleted(this, new EstraiTracciatoAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnEstraiTracciatoAEOperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/GetFlussiTracciati", RequestElementName="GetFlussiTracciati", RequestNamespace="http://localhost/OPENaeWS/", ResponseElementName="GetFlussiTracciatiResponse", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetFlussiTracciatiResult")]
        public objFlussoAE[] GetFlussiTracciatiAE(string sTributo, string sCodiceISTAT, ref string sMyErr) {
            object[] results = this.Invoke("GetFlussiTracciatiAE", new object[] {
                        sTributo,
                        sCodiceISTAT,
                        sMyErr});
            sMyErr = ((string)(results[1]));
            return ((objFlussoAE[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFlussiTracciatiAE(string sTributo, string sCodiceISTAT, string sMyErr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFlussiTracciatiAE", new object[] {
                        sTributo,
                        sCodiceISTAT,
                        sMyErr}, callback, asyncState);
        }
        
        /// <remarks/>
        public objFlussoAE[] EndGetFlussiTracciatiAE(System.IAsyncResult asyncResult, out string sMyErr) {
            object[] results = this.EndInvoke(asyncResult);
            sMyErr = ((string)(results[1]));
            return ((objFlussoAE[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFlussiTracciatiAEAsync(string sTributo, string sCodiceISTAT, string sMyErr) {
            this.GetFlussiTracciatiAEAsync(sTributo, sCodiceISTAT, sMyErr, null);
        }
        
        /// <remarks/>
        public void GetFlussiTracciatiAEAsync(string sTributo, string sCodiceISTAT, string sMyErr, object userState) {
            try { 
            if ((this.GetFlussiTracciatiAEOperationCompleted == null)) {
                this.GetFlussiTracciatiAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlussiTracciatiAEOperationCompleted);
            }
            this.InvokeAsync("GetFlussiTracciatiAE", new object[] {
                        sTributo,
                        sCodiceISTAT,
                        sMyErr}, this.GetFlussiTracciatiAEOperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.GetFlussiTracciatiAEAsync.errore: ", Err);
            }
        }
        
        private void OnGetFlussiTracciatiAEOperationCompleted(object arg) {
            try { 
            if ((this.GetFlussiTracciatiAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlussiTracciatiAECompleted(this, new GetFlussiTracciatiAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnGetFlussiTracciatiAEOperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="PopolaTabAppoggioAE2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/PopolaDaFile", RequestElementName="PopolaDaFile", RequestNamespace="http://localhost/OPENaeWS/", ResponseElementName="PopolaDaFileResponse", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PopolaDaFileResult")]
        public bool PopolaTabAppoggioAE(string sTributo, string sAnnoRif, string sCodiceISTAT, string sFileImport, string sProvenienza) {
            object[] results = this.Invoke("PopolaTabAppoggioAE2", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sFileImport,
                        sProvenienza});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPopolaTabAppoggioAE2(string sTributo, string sAnnoRif, string sCodiceISTAT, string sFileImport, string sProvenienza, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PopolaTabAppoggioAE2", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sFileImport,
                        sProvenienza}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndPopolaTabAppoggioAE2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAE2Async(string sTributo, string sAnnoRif, string sCodiceISTAT, string sFileImport, string sProvenienza) {
            this.PopolaTabAppoggioAE2Async(sTributo, sAnnoRif, sCodiceISTAT, sFileImport, sProvenienza, null);
        }
        
        /// <remarks/>
        public void PopolaTabAppoggioAE2Async(string sTributo, string sAnnoRif, string sCodiceISTAT, string sFileImport, string sProvenienza, object userState) {
            try { 
            if ((this.PopolaTabAppoggioAE2OperationCompleted == null)) {
                this.PopolaTabAppoggioAE2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopolaTabAppoggioAE2OperationCompleted);
            }
            this.InvokeAsync("PopolaTabAppoggioAE2", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sFileImport,
                        sProvenienza}, this.PopolaTabAppoggioAE2OperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.PopolaTabAppoggioAE2Async.errore: ", Err);
            }
        }
        
        private void OnPopolaTabAppoggioAE2OperationCompleted(object arg) {
            try { 
            if ((this.PopolaTabAppoggioAE2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopolaTabAppoggioAE2Completed(this, new PopolaTabAppoggioAE2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnPopolaTabAppoggioAE2OperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="EstraiTracciatoAE1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/OPENaeWS/EstraiICI", RequestElementName="EstraiICI", RequestNamespace="http://localhost/OPENaeWS/", ResponseElementName="EstraiICIResponse", ResponseNamespace="http://localhost/OPENaeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EstraiICIResult")]
        public string EstraiTracciatoAE(string sTributo, string sAnnoRif, string sCodiceISTAT, string sCodBelfiore, string sDescrEnte, string sCAPEnte, string sDataScadenza, int nProgInvio, ref string sNomeFileTracciati) {
            object[] results = this.Invoke("EstraiTracciatoAE1", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sCodBelfiore,
                        sDescrEnte,
                        sCAPEnte,
                        sDataScadenza,
                        nProgInvio,
                        sNomeFileTracciati});
            sNomeFileTracciati = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEstraiTracciatoAE1(string sTributo, string sAnnoRif, string sCodiceISTAT, string sCodBelfiore, string sDescrEnte, string sCAPEnte, string sDataScadenza, int nProgInvio, string sNomeFileTracciati, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EstraiTracciatoAE1", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sCodBelfiore,
                        sDescrEnte,
                        sCAPEnte,
                        sDataScadenza,
                        nProgInvio,
                        sNomeFileTracciati}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndEstraiTracciatoAE1(System.IAsyncResult asyncResult, out string sNomeFileTracciati) {
            object[] results = this.EndInvoke(asyncResult);
            sNomeFileTracciati = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EstraiTracciatoAE1Async(string sTributo, string sAnnoRif, string sCodiceISTAT, string sCodBelfiore, string sDescrEnte, string sCAPEnte, string sDataScadenza, int nProgInvio, string sNomeFileTracciati) {
            this.EstraiTracciatoAE1Async(sTributo, sAnnoRif, sCodiceISTAT, sCodBelfiore, sDescrEnte, sCAPEnte, sDataScadenza, nProgInvio, sNomeFileTracciati, null);
        }
        
        /// <remarks/>
        public void EstraiTracciatoAE1Async(string sTributo, string sAnnoRif, string sCodiceISTAT, string sCodBelfiore, string sDescrEnte, string sCAPEnte, string sDataScadenza, int nProgInvio, string sNomeFileTracciati, object userState) {
            try { 
            if ((this.EstraiTracciatoAE1OperationCompleted == null)) {
                this.EstraiTracciatoAE1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstraiTracciatoAE1OperationCompleted);
            }
            this.InvokeAsync("EstraiTracciatoAE1", new object[] {
                        sTributo,
                        sAnnoRif,
                        sCodiceISTAT,
                        sCodBelfiore,
                        sDescrEnte,
                        sCAPEnte,
                        sDataScadenza,
                        nProgInvio,
                        sNomeFileTracciati}, this.EstraiTracciatoAE1OperationCompleted, userState);
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.EstraiTracciatoAE1Async.errore: ", Err);
            }
        }
        
        private void OnEstraiTracciatoAE1OperationCompleted(object arg) {
            try { 
            if ((this.EstraiTracciatoAE1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstraiTracciatoAE1Completed(this, new EstraiTracciatoAE1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.OnEstraiTracciatoAE1OperationCompleted.errore: ", Err);
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            try { 
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
            }
            catch (Exception Err)
            {
                log.Debug(Business.ConstWrapper.CodiceEnte + "."+ Business.ConstWrapper.sUsername + " - DichiarazioniICI.ServiceOPENae.IsLocalFileSystemWebService.errore: ", Err);
                throw Err;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public partial class DisposizioneAE {
        
        private int nIDDisposizioneField;
        
        private int nIDCollegamentoField;
        
        private int nIDFlussoField;
        
        private int nIDContribuenteField;
        
        private int nMesiFatturazioneField;
        
        private int nConsumoField;
        
        private double nImportoFatturatoField;
        
        private TitoloOccupazione nIDTitoloOccupazioneField;
        
        private NaturaOccupazione nIDTipoOccupanteField;
        
        private DestinazioneUso nIDDestinazioneUsoField;
        
        private AssenzaDatiCatastali nIDAssenzaDatiCatastaliField;
        
        private TipologiaUtenza nIDTipoUtenzaField;
        
        private string sCodISTATField;
        
        private string sTributoField;
        
        private string sAnnoField;
        
        private string sCodFiscaleEnteField;
        
        private string sCognomeEnteField;
        
        private string sNomeEnteField;
        
        private string sSessoEnteField;
        
        private string sDataNascitaEnteField;
        
        private string sComuneNascitaSedeEnteField;
        
        private string sPVNascitaSedeEnteField;
        
        private string sCodFiscaleField;
        
        private string sCognomeField;
        
        private string sNomeField;
        
        private string sSessoField;
        
        private string sDataNascitaField;
        
        private string sComuneNascitaSedeField;
        
        private string sPVNascitaSedeField;
        
        private string sComuneDomFiscField;
        
        private string sPVDomFiscField;
        
        private string sEstremiContrattoField;
        
        private string sTipoContrattoField;
        
        private string sDataInizioField;
        
        private string sDataFineField;
        
        private string sComuneAmmUbicazioneField;
        
        private string sPVAmmUbicazioneField;
        
        private string sComuneCatastUbicazioneField;
        
        private string sCodComuneUbicazioneCatastField;
        
        private string sIDTipoUnitaField;
        
        private string sSezioneField;
        
        private string sFoglioField;
        
        private string sParticellaField;
        
        private string sEstensioneParticellaField;
        
        private string sIDTipoParticellaField;
        
        private string sSubalternoField;
        
        private string sIndirizzoField;
        
        private string sCivicoField;
        
        private string sInternoField;
        
        private string sScalaField;
        
        private string sSegnoField;
        
        /// <remarks/>
        public int nIDDisposizione {
            get {
                return this.nIDDisposizioneField;
            }
            set {
                this.nIDDisposizioneField = value;
            }
        }
        
        /// <remarks/>
        public int nIDCollegamento {
            get {
                return this.nIDCollegamentoField;
            }
            set {
                this.nIDCollegamentoField = value;
            }
        }
        
        /// <remarks/>
        public int nIDFlusso {
            get {
                return this.nIDFlussoField;
            }
            set {
                this.nIDFlussoField = value;
            }
        }
        
        /// <remarks/>
        public int nIDContribuente {
            get {
                return this.nIDContribuenteField;
            }
            set {
                this.nIDContribuenteField = value;
            }
        }
        
        /// <remarks/>
        public int nMesiFatturazione {
            get {
                return this.nMesiFatturazioneField;
            }
            set {
                this.nMesiFatturazioneField = value;
            }
        }
        
        /// <remarks/>
        public int nConsumo {
            get {
                return this.nConsumoField;
            }
            set {
                this.nConsumoField = value;
            }
        }
        
        /// <remarks/>
        public double nImportoFatturato {
            get {
                return this.nImportoFatturatoField;
            }
            set {
                this.nImportoFatturatoField = value;
            }
        }
        
        /// <remarks/>
        public TitoloOccupazione nIDTitoloOccupazione {
            get {
                return this.nIDTitoloOccupazioneField;
            }
            set {
                this.nIDTitoloOccupazioneField = value;
            }
        }
        
        /// <remarks/>
        public NaturaOccupazione nIDTipoOccupante {
            get {
                return this.nIDTipoOccupanteField;
            }
            set {
                this.nIDTipoOccupanteField = value;
            }
        }
        
        /// <remarks/>
        public DestinazioneUso nIDDestinazioneUso {
            get {
                return this.nIDDestinazioneUsoField;
            }
            set {
                this.nIDDestinazioneUsoField = value;
            }
        }
        
        /// <remarks/>
        public AssenzaDatiCatastali nIDAssenzaDatiCatastali {
            get {
                return this.nIDAssenzaDatiCatastaliField;
            }
            set {
                this.nIDAssenzaDatiCatastaliField = value;
            }
        }
        
        /// <remarks/>
        public TipologiaUtenza nIDTipoUtenza {
            get {
                return this.nIDTipoUtenzaField;
            }
            set {
                this.nIDTipoUtenzaField = value;
            }
        }
        
        /// <remarks/>
        public string sCodISTAT {
            get {
                return this.sCodISTATField;
            }
            set {
                this.sCodISTATField = value;
            }
        }
        
        /// <remarks/>
        public string sTributo {
            get {
                return this.sTributoField;
            }
            set {
                this.sTributoField = value;
            }
        }
        
        /// <remarks/>
        public string sAnno {
            get {
                return this.sAnnoField;
            }
            set {
                this.sAnnoField = value;
            }
        }
        
        /// <remarks/>
        public string sCodFiscaleEnte {
            get {
                return this.sCodFiscaleEnteField;
            }
            set {
                this.sCodFiscaleEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sCognomeEnte {
            get {
                return this.sCognomeEnteField;
            }
            set {
                this.sCognomeEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sNomeEnte {
            get {
                return this.sNomeEnteField;
            }
            set {
                this.sNomeEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sSessoEnte {
            get {
                return this.sSessoEnteField;
            }
            set {
                this.sSessoEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sDataNascitaEnte {
            get {
                return this.sDataNascitaEnteField;
            }
            set {
                this.sDataNascitaEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sComuneNascitaSedeEnte {
            get {
                return this.sComuneNascitaSedeEnteField;
            }
            set {
                this.sComuneNascitaSedeEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sPVNascitaSedeEnte {
            get {
                return this.sPVNascitaSedeEnteField;
            }
            set {
                this.sPVNascitaSedeEnteField = value;
            }
        }
        
        /// <remarks/>
        public string sCodFiscale {
            get {
                return this.sCodFiscaleField;
            }
            set {
                this.sCodFiscaleField = value;
            }
        }
        
        /// <remarks/>
        public string sCognome {
            get {
                return this.sCognomeField;
            }
            set {
                this.sCognomeField = value;
            }
        }
        
        /// <remarks/>
        public string sNome {
            get {
                return this.sNomeField;
            }
            set {
                this.sNomeField = value;
            }
        }
        
        /// <remarks/>
        public string sSesso {
            get {
                return this.sSessoField;
            }
            set {
                this.sSessoField = value;
            }
        }
        
        /// <remarks/>
        public string sDataNascita {
            get {
                return this.sDataNascitaField;
            }
            set {
                this.sDataNascitaField = value;
            }
        }
        
        /// <remarks/>
        public string sComuneNascitaSede {
            get {
                return this.sComuneNascitaSedeField;
            }
            set {
                this.sComuneNascitaSedeField = value;
            }
        }
        
        /// <remarks/>
        public string sPVNascitaSede {
            get {
                return this.sPVNascitaSedeField;
            }
            set {
                this.sPVNascitaSedeField = value;
            }
        }
        
        /// <remarks/>
        public string sComuneDomFisc {
            get {
                return this.sComuneDomFiscField;
            }
            set {
                this.sComuneDomFiscField = value;
            }
        }
        
        /// <remarks/>
        public string sPVDomFisc {
            get {
                return this.sPVDomFiscField;
            }
            set {
                this.sPVDomFiscField = value;
            }
        }
        
        /// <remarks/>
        public string sEstremiContratto {
            get {
                return this.sEstremiContrattoField;
            }
            set {
                this.sEstremiContrattoField = value;
            }
        }
        
        /// <remarks/>
        public string sTipoContratto {
            get {
                return this.sTipoContrattoField;
            }
            set {
                this.sTipoContrattoField = value;
            }
        }
        
        /// <remarks/>
        public string sDataInizio {
            get {
                return this.sDataInizioField;
            }
            set {
                this.sDataInizioField = value;
            }
        }
        
        /// <remarks/>
        public string sDataFine {
            get {
                return this.sDataFineField;
            }
            set {
                this.sDataFineField = value;
            }
        }
        
        /// <remarks/>
        public string sComuneAmmUbicazione {
            get {
                return this.sComuneAmmUbicazioneField;
            }
            set {
                this.sComuneAmmUbicazioneField = value;
            }
        }
        
        /// <remarks/>
        public string sPVAmmUbicazione {
            get {
                return this.sPVAmmUbicazioneField;
            }
            set {
                this.sPVAmmUbicazioneField = value;
            }
        }
        
        /// <remarks/>
        public string sComuneCatastUbicazione {
            get {
                return this.sComuneCatastUbicazioneField;
            }
            set {
                this.sComuneCatastUbicazioneField = value;
            }
        }
        
        /// <remarks/>
        public string sCodComuneUbicazioneCatast {
            get {
                return this.sCodComuneUbicazioneCatastField;
            }
            set {
                this.sCodComuneUbicazioneCatastField = value;
            }
        }
        
        /// <remarks/>
        public string sIDTipoUnita {
            get {
                return this.sIDTipoUnitaField;
            }
            set {
                this.sIDTipoUnitaField = value;
            }
        }
        
        /// <remarks/>
        public string sSezione {
            get {
                return this.sSezioneField;
            }
            set {
                this.sSezioneField = value;
            }
        }
        
        /// <remarks/>
        public string sFoglio {
            get {
                return this.sFoglioField;
            }
            set {
                this.sFoglioField = value;
            }
        }
        
        /// <remarks/>
        public string sParticella {
            get {
                return this.sParticellaField;
            }
            set {
                this.sParticellaField = value;
            }
        }
        
        /// <remarks/>
        public string sEstensioneParticella {
            get {
                return this.sEstensioneParticellaField;
            }
            set {
                this.sEstensioneParticellaField = value;
            }
        }
        
        /// <remarks/>
        public string sIDTipoParticella {
            get {
                return this.sIDTipoParticellaField;
            }
            set {
                this.sIDTipoParticellaField = value;
            }
        }
        
        /// <remarks/>
        public string sSubalterno {
            get {
                return this.sSubalternoField;
            }
            set {
                this.sSubalternoField = value;
            }
        }
        
        /// <remarks/>
        public string sIndirizzo {
            get {
                return this.sIndirizzoField;
            }
            set {
                this.sIndirizzoField = value;
            }
        }
        
        /// <remarks/>
        public string sCivico {
            get {
                return this.sCivicoField;
            }
            set {
                this.sCivicoField = value;
            }
        }
        
        /// <remarks/>
        public string sInterno {
            get {
                return this.sInternoField;
            }
            set {
                this.sInternoField = value;
            }
        }
        
        /// <remarks/>
        public string sScala {
            get {
                return this.sScalaField;
            }
            set {
                this.sScalaField = value;
            }
        }
        
        /// <remarks/>
        public string sSegno {
            get {
                return this.sSegnoField;
            }
            set {
                this.sSegnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public enum TitoloOccupazione {
        
        /// <remarks/>
        NonSpecificato,
        
        /// <remarks/>
        Proprieta,
        
        /// <remarks/>
        Usufrutto,
        
        /// <remarks/>
        Locazione_AltroDiritto,
        
        /// <remarks/>
        AltroDiritto_Rappresentante,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public enum NaturaOccupazione {
        
        /// <remarks/>
        NonSpecificato,
        
        /// <remarks/>
        Singolo,
        
        /// <remarks/>
        NucleoFamiliare,
        
        /// <remarks/>
        AttivitaCommerciale,
        
        /// <remarks/>
        AltraTipologia,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public enum DestinazioneUso {
        
        /// <remarks/>
        NonSpecificato,
        
        /// <remarks/>
        Abitativo,
        
        /// <remarks/>
        TenutoADisposizione,
        
        /// <remarks/>
        Commerciale,
        
        /// <remarks/>
        Box,
        
        /// <remarks/>
        AltriUsi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public enum AssenzaDatiCatastali {
        
        /// <remarks/>
        NonSpecificato,
        
        /// <remarks/>
        NonAccatastato,
        
        /// <remarks/>
        NonAccatastabile,
        
        /// <remarks/>
        DatiNonDisponibili_Preesistente,
        
        /// <remarks/>
        OmessaDichiarazione,
        
        /// <remarks/>
        FornitureTemporanee,
        
        /// <remarks/>
        Condominii,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public enum TipologiaUtenza {
        
        /// <remarks/>
        NonSpecificato,
        
        /// <remarks/>
        DomesticaRes,
        
        /// <remarks/>
        DomesticaNonRes,
        
        /// <remarks/>
        NonDomestica,
        
        /// <remarks/>
        GrandeUtenza,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/OPENaeWS/")]
    public partial class objFlussoAE {
        
        private int idFlussoField;
        
        private string codiceISTATField;
        
        private string annoField;
        
        private string nomeFileField;
        
        private string dataEstrazioneField;
        
        private int numeroUtentiField;
        
        private int numeroRecordsField;
        
        private int numeroArticoliField;
        
        /// <remarks/>
        public int IdFlusso {
            get {
                return this.idFlussoField;
            }
            set {
                this.idFlussoField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceISTAT {
            get {
                return this.codiceISTATField;
            }
            set {
                this.codiceISTATField = value;
            }
        }
        
        /// <remarks/>
        public string Anno {
            get {
                return this.annoField;
            }
            set {
                this.annoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFile {
            get {
                return this.nomeFileField;
            }
            set {
                this.nomeFileField = value;
            }
        }
        
        /// <remarks/>
        public string DataEstrazione {
            get {
                return this.dataEstrazioneField;
            }
            set {
                this.dataEstrazioneField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroUtenti {
            get {
                return this.numeroUtentiField;
            }
            set {
                this.numeroUtentiField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroRecords {
            get {
                return this.numeroRecordsField;
            }
            set {
                this.numeroRecordsField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroArticoli {
            get {
                return this.numeroArticoliField;
            }
            set {
                this.numeroArticoliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PopolaTabAppoggioAECompletedEventHandler(object sender, PopolaTabAppoggioAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopolaTabAppoggioAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopolaTabAppoggioAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PopolaTabAppoggioAE1CompletedEventHandler(object sender, PopolaTabAppoggioAE1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopolaTabAppoggioAE1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopolaTabAppoggioAE1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EstraiTracciatoAECompletedEventHandler(object sender, EstraiTracciatoAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstraiTracciatoAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstraiTracciatoAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sNomeFileTracciati {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetFlussiTracciatiAECompletedEventHandler(object sender, GetFlussiTracciatiAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlussiTracciatiAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlussiTracciatiAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public objFlussoAE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((objFlussoAE[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMyErr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PopolaTabAppoggioAE2CompletedEventHandler(object sender, PopolaTabAppoggioAE2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PopolaTabAppoggioAE2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PopolaTabAppoggioAE2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EstraiTracciatoAE1CompletedEventHandler(object sender, EstraiTracciatoAE1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstraiTracciatoAE1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstraiTracciatoAE1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sNomeFileTracciati {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591